# -*- coding: utf-8 -*-
"""import_csv_mysql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5Dy04fWGKtOgb8BV2RGfTzY3LcgcTBm
"""

# pip install pandas mysql-connector-python

import pandas as pd
import mysql.connector
import numpy as np

# KONEKSI DATABASE
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Yue54345",
    database="crawling_db"
)

cursor = conn.cursor()

df = pd.read_csv(
    "cleaned.csv",
    sep=',',
    encoding='utf-8',
    na_filter=True
)

df = df.replace('', None)
df = df.replace(np.nan, None)

print("\nAfter cleaning with np.nan:")
print(df.head())

for index, row in df.iterrows():

    sql = """
    INSERT INTO mobil_bekas (
        Brand,
        model,
        Year,
        Age,
        kmDriven,
        Transmission,
        Owner,
        FuelType,
        PostedDate,
        AdditionInfo,
        AskPrice,
        Harga
    )
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """

    values = (
        row['Brand'] if pd.notna(row['Brand']) else None,
        row['model'] if pd.notna(row['model']) else None,
        row['Year'] if pd.notna(row['Year']) else None,
        row['Age'] if pd.notna(row['Age']) else None,
        row['kmDriven'] if pd.notna(row['kmDriven']) else None,
        row['Transmission'] if pd.notna(row['Transmission']) else None,
        row['Owner'] if pd.notna(row['Owner']) else None,
        row['FuelType'] if pd.notna(row['FuelType']) else None,
        row['PostedDate'] if pd.notna(row['PostedDate']) else None,
        row['AdditionInfo'] if pd.notna(row['AdditionInfo']) else None,
        row['AskPrice'] if pd.notna(row['AskPrice']) else None,
        row['Harga'] if pd.notna(row['Harga']) else None
    )

    cursor.execute(sql, values)

conn.commit()

print("Data berhasil dimasukkan ke database")

